### PR TITLE
adding troubleshooting section

### PR DESCRIPTION
**Pull request by aerickson**
Adding a troubleshooting section with two things that caused me problems.

### CODE REVIEW

**Comment by tazjin** [comment]
Thank you for this, we literally just wasted two hours on the first bullet point you added there and it would never have occured to me what the solution is! 😌

**Comment by WishCow** [comment]
Just ran into this, thank you.

**Comment by M22an** [comment]
Thanks for this @aerickson, I was stuck for hours and this saved me.

**Comment by atomita** [comment]
Thanks! Also, sorry for the delay in response.

**Pull request merged**
