### PR TITLE
Update fluent-plugin-elasticsearch version

### PR DESCRIPTION
**Pull request by yissachar**
2.0.0 has now been released so we shouldn't use the RC version.

cc @cosmo0920

### CODE REVIEW

**Comment by cosmo0920** [comment]
:+1: Thanks for notifying it!

**Comment by cosmo0920** [comment]
Could you update fluent-plugin-elasticsearch dependency in [gemspec](https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/blob/master/fluent-plugin-aws-elasticsearch-service.gemspec#L28)?

**Comment by yissachar** [comment]
Updated, thanks for catching that!

**Comment by eigokor** [comment]
Can we expect it to be 2.9.0 ?

**Comment by cosmo0920** [comment]
Yes!

**Pull request closed without merging**
